/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,vue}"],
    theme: {
        fontFamily: {
            sans: "var(--font-family-default)",
            mono: "var(--font-family-code)",
        },
        fontWeight: {
            regular: "var(--font-weight-regular)",
            medium: "var(--font-weight-medium)",
            bold: "var(--font-weight-bold)",
        },
        fontSize: {
            small: "var(--font-size-small)",
            default: "var(--font-size-default)",
            "subhead-default": "var(--font-size-subhead-default)",
            "subhead-big": "var(--font-size-subhead-big)",
            "header-default": "var(--font-size-header-default)",
            "header-big": "var(--font-size-header-big)",
        },
        lineHeight: {
            small: "var(--line-height-small)",
            default: "var(--line-height-default)",
            "subhead-default": "var(--line-height-subhead-default)",
            "subhead-big": "var(--line-height-subhead-big)",
            "header-default": "var(--line-height-header-default)",
            "header-big": "var(--line-height-header-big)",
        },
        borderRadius: {
            1: "var(--border-radius-1)",
            2: "var(--border-radius-2)",
            4: "var(--border-radius-4)",
            8: "var(--border-radius-8)",
            12: "var(--border-radius-12)",
            16: "var(--border-radius-16)",
            default: "var(--border-radius-default)",
            full: "var(--border-radius-round)",
        },
        boxShadow: {
            1: "var(--shadow-1)",
            2: "var(--shadow-2)",
            3: "var(--shadow-3)",
            default: "var(--shadow-default)",
        },
        spacing: {
            2: "var(--space-2)",
            4: "var(--space-4)",
            8: "var(--space-8)",
            12: "var(--space-12)",
            16: "var(--space-16)",
            24: "var(--space-24)",
            32: "var(--space-32)",
            48: "var(--space-48)",
            64: "var(--space-64)",
            128: "var(--space-128)",
            256: "var(--space-256)",
            default: "var(--space-default)",
        },
        colors: {
            transparent: "transparent",
            white: "var(--white)",
            black: "var(--black)",
            background: {
                root: "var(--background-root)",
                default: "var(--background-default)",
                higher: "var(--background-higher)",
                highest: "var(--background-highest)",
                overlay: "var(--background-overlay)",
            },
            foreground: {
                default: "var(--foreground-default)",
                dimmer: "var(--foreground-dimmer)",
                dimmest: "var(--foreground-dimmest)",
            },
            outline: {
                dimmest: "var(--outline-dimmest)",
                dimmer: "var(--outline-dimmer)",
                default: "var(--outline-default)",
                stronger: "var(--outline-stronger)",
                strongest: "var(--outline-strongest)",
            },
            accent: {
                primary: {
                    dimmest: "var(--accent-primary-dimmest)",
                    dimmer: "var(--accent-primary-dimmer)",
                    default: "var(--accent-primary-default)",
                    stronger: "var(--accent-primary-stronger)",
                    strongest: "var(--accent-primary-strongest)",
                },
                positive: {
                    dimmest: "var(--accent-positive-dimmest)",
                    dimmer: "var(--accent-positive-dimmer)",
                    default: "var(--accent-positive-default)",
                    stronger: "var(--accent-positive-stronger)",
                    strongest: "var(--accent-positive-strongest)",
                },
                negative: {
                    dimmest: "var(--accent-negative-dimmest)",
                    dimmer: "var(--accent-negative-dimmer)",
                    default: "var(--accent-negative-default)",
                    stronger: "var(--accent-negative-stronger)",
                    strongest: "var(--accent-negative-strongest)",
                },
                red: {
                    dimmest: "var(--accent-red-dimmest)",
                    dimmer: "var(--accent-red-dimmer)",
                    default: "var(--accent-red-default)",
                    stronger: "var(--accent-red-stronger)",
                    strongest: "var(--accent-red-strongest)",
                },
                orange: {
                    dimmest: "var(--accent-orange-dimmest)",
                    dimmer: "var(--accent-orange-dimmer)",
                    default: "var(--accent-orange-default)",
                    stronger: "var(--accent-orange-stronger)",
                    strongest: "var(--accent-orange-strongest)",
                },
                yellow: {
                    dimmest: "var(--accent-yellow-dimmest)",
                    dimmer: "var(--accent-yellow-dimmer)",
                    default: "var(--accent-yellow-default)",
                    stronger: "var(--accent-yellow-stronger)",
                    strongest: "var(--accent-yellow-strongest)",
                },
                lime: {
                    dimmest: "var(--accent-lime-dimmest)",
                    dimmer: "var(--accent-lime-dimmer)",
                    default: "var(--accent-lime-default)",
                    stronger: "var(--accent-lime-stronger)",
                    strongest: "var(--accent-lime-strongest)",
                },
                green: {
                    dimmest: "var(--accent-green-dimmest)",
                    dimmer: "var(--accent-green-dimmer)",
                    default: "var(--accent-green-default)",
                    stronger: "var(--accent-green-stronger)",
                    strongest: "var(--accent-green-strongest)",
                },
                teal: {
                    dimmest: "var(--accent-teal-dimmest)",
                    dimmer: "var(--accent-teal-dimmer)",
                    default: "var(--accent-teal-default)",
                    stronger: "var(--accent-teal-stronger)",
                    strongest: "var(--accent-teal-strongest)",
                },
                blue: {
                    dimmest: "var(--accent-blue-dimmest)",
                    dimmer: "var(--accent-blue-dimmer)",
                    default: "var(--accent-blue-default)",
                    stronger: "var(--accent-blue-stronger)",
                    strongest: "var(--accent-blue-strongest)",
                },
                blurple: {
                    dimmest: "var(--accent-blurple-dimmest)",
                    dimmer: "var(--accent-blurple-dimmer)",
                    default: "var(--accent-blurple-default)",
                    stronger: "var(--accent-blurple-stronger)",
                    strongest: "var(--accent-blurple-strongest)",
                },
                purple: {
                    dimmest: "var(--accent-purple-dimmest)",
                    dimmer: "var(--accent-purple-dimmer)",
                    default: "var(--accent-purple-default)",
                    stronger: "var(--accent-purple-stronger)",
                    strongest: "var(--accent-purple-strongest)",
                },
                magenta: {
                    dimmest: "var(--accent-magenta-dimmest)",
                    dimmer: "var(--accent-magenta-dimmer)",
                    default: "var(--accent-magenta-default)",
                    stronger: "var(--accent-magenta-stronger)",
                    strongest: "var(--accent-magenta-strongest)",
                },
                pink: {
                    dimmest: "var(--accent-pink-dimmest)",
                    dimmer: "var(--accent-pink-dimmer)",
                    default: "var(--accent-pink-default)",
                    stronger: "var(--accent-pink-stronger)",
                    strongest: "var(--accent-pink-strongest)",
                },
                grey: {
                    dimmest: "var(--accent-grey-dimmest)",
                    dimmer: "var(--accent-grey-dimmer)",
                    default: "var(--accent-grey-default)",
                    stronger: "var(--accent-grey-stronger)",
                    strongest: "var(--accent-grey-strongest)",
                },
                brown: {
                    dimmest: "var(--accent-brown-dimmest)",
                    dimmer: "var(--accent-brown-dimmer)",
                    default: "var(--accent-brown-default)",
                    stronger: "var(--accent-brown-stronger)",
                    strongest: "var(--accent-brown-strongest)",
                },
            },
        },
        transitionDuration: {
            snappy: "var(--transition-duration-snappy)",
            chill: "var(--transition-duration-chill)",
        },
        transitionTimingFunction: {
            snappy: "var(--transition-timing-function-snappy)",
            chill: "var(--transition-timing-function-chill)",
        },
        borderWidth: {
            default: "var(--border-width-default)",
        },
    },
    plugins: [],
};
